### ISSUE TITLE
Why can’t our team use APS services?

### ISSUE THREAD

**Issue by pp840814** [autodesk-platform-services/aps-iot-extensions-demo#17]
Please tell me why our team cannot use the APS service. I will send you a video to understand the situation.
Through the program code error report, I learned that the main reason is that the BIM model cannot be read, but we have uploaded it and the account has not expired.

We could have used APS service.
![image](https://github.com/autodesk-platform-services/aps-iot-extensions-demo/assets/103113630/93b5e396-50a7-4c10-b848-e065f1b6bacc)

**Comment by yiskang** [comment]
(remove your demo video as you exposed your APS credentials to the public in the recording. Please go to https://aps.autodesk.com/myapps/ to reset)

I'm sorry to hear this issue is bothering you, but HTTP error code 404 means the Model Derivative service cannot find any model associated with your URN in the above snapshot. Please load it in a simple viewer app to check if the viewer can open the model without any problem to help narrow down the issue.

If it does, please check if you have the URN well-configured in https://github.com/autodesk-platform-services/aps-iot-extensions-demo/blob/master/public/config.js following the step 4 of https://github.com/autodesk-platform-services/aps-iot-extensions-demo?tab=readme-ov-file#running-locally.


Or specify the viewer env and api explicitly at https://github.com/autodesk-platform-services/aps-iot-extensions-demo/blob/master/public/viewer.js#L34 like below:

```js

export function initViewer(container, extensions) {
    return new Promise(function (resolve, reject) {
        Autodesk.Viewing.Initializer({ getAccessToken, env: 'AutodeskProduction2', api: 'streamingV2' }, function () {
            const viewer = new Autodesk.Viewing.GuiViewer3D(container, { extensions });
            viewer.start();
            resolve(viewer);
        });
    });
}
```

**Comment by libvarun** [comment]
@pp840814 Have you tried Eason's solution? Can we close this issue? Please let us know.

**Comment by pp840814** [comment]
Hello,

After reading this, we understand the problem points
At present, the model has been reacquired by adjusting the API.
Thanks!

varun patil ***@***.***> 於 2024年3月1日 週五 下午4:38寫道：

**Comment by libvarun** [comment]
Thanks for the confirmation.
